class CarBrand {
  final String name;
  final String iconPath;

  CarBrand({required this.name, required this.iconPath});
}

List<CarBrand> carBrands = [
  CarBrand(name: 'Alfa Romeo', iconPath: '/assets/icons/alfa_romeo.png'),
  CarBrand(name: 'Aston Martin', iconPath: '/assets/icons/aston_martin.png'),
  CarBrand(name: 'Audi', iconPath: '/assets/icons/audi.png'),
  CarBrand(name: 'Bentley', iconPath: '/assets/icons/bentley.png'),
  CarBrand(name: 'BMW', iconPath: '/assets/icons/bmw.png'),
  CarBrand(name: 'Borgward', iconPath: '/assets/icons/borgward.png'),
  CarBrand(name: 'Bufori', iconPath: '/assets/icons/bufori.png'),
  CarBrand(name: 'BYD', iconPath: '/assets/icons/byd.png'),
  CarBrand(name: 'Caterham', iconPath: '/assets/icons/caterham.png'),
  CarBrand(name: 'Chana', iconPath: '/assets/icons/chana.png'),
  CarBrand(name: 'Chery', iconPath: '/assets/icons/chery.png'),
  CarBrand(name: 'Chevrolet', iconPath: '/assets/icons/chevrolet.png'),
  CarBrand(name: 'Citroen', iconPath: '/assets/icons/citroen.png'),
  CarBrand(name: 'Ferrari', iconPath: '/assets/icons/ferrari.png'),
  CarBrand(name: 'Fiat', iconPath: '/assets/icons/fiat.png'),
  CarBrand(name: 'Ford', iconPath: '/assets/icons/ford.png'),
  CarBrand(name: 'GAC', iconPath: '/assets/icons/gac.png'),
  CarBrand(name: 'Great Wall', iconPath: '/assets/icons/great_wall.png'),
  CarBrand(name: 'Haval', iconPath: '/assets/icons/haval.png'),
  CarBrand(name: 'Honda', iconPath: '/assets/icons/honda.png'),
  CarBrand(name: 'Hyundai', iconPath: '/assets/icons/hyundai.png'),
  CarBrand(name: 'Infiniti', iconPath: '/assets/icons/infiniti.png'),
  CarBrand(name: 'Isuzu', iconPath: '/assets/icons/isuzu.png'),
  CarBrand(name: 'Jaguar', iconPath: '/assets/icons/jaguar.png'),
  CarBrand(name: 'Jeep', iconPath: '/assets/icons/jeep.png'),
  CarBrand(name: 'JMC', iconPath: '/assets/icons/jmc.png'),
  CarBrand(name: 'Kia', iconPath: '/assets/icons/kia.png'),
  CarBrand(name: 'Lamborghini', iconPath: '/assets/icons/lamborghini.png'),
  CarBrand(name: 'Land Rover', iconPath: '/assets/icons/land_rover.png'),
  CarBrand(name: 'Lexus', iconPath: '/assets/icons/lexus.png'),
  CarBrand(name: 'Lotus', iconPath: '/assets/icons/lotus.png'),
  CarBrand(name: 'Mahindra', iconPath: '/assets/icons/mahindra.png'),
  CarBrand(name: 'Maserati', iconPath: '/assets/icons/maserati.png'),
  CarBrand(name: 'Maxus', iconPath: '/assets/icons/maxus.png'),
  CarBrand(name: 'Mazda', iconPath: '/assets/icons/mazda.png'),
  CarBrand(name: 'McLaren', iconPath: '/assets/icons/mclaren.png'),
  CarBrand(name: 'Mercedes-Benz', iconPath: '/assets/icons/mercedes_benz.png'),
  CarBrand(name: 'MG', iconPath: '/assets/icons/mg.png'),
  CarBrand(name: 'MINI', iconPath: '/assets/icons/mini.png'),
  CarBrand(name: 'Mitsubishi', iconPath: '/assets/icons/mitsubishi.png'),
  CarBrand(name: 'Neta', iconPath: '/assets/icons/neta.png'),
  CarBrand(name: 'Nissan', iconPath: '/assets/icons/nissan.png'),
  CarBrand(name: 'Perodua', iconPath: '/assets/icons/perodua.png'),
  CarBrand(name: 'Peugeot', iconPath: '/assets/icons/peugeot.png'),
  CarBrand(name: 'Porsche', iconPath: '/assets/icons/porsche.png'),
  CarBrand(name: 'Proton', iconPath: '/assets/icons/proton.png'),
  CarBrand(name: 'Renault', iconPath: '/assets/icons/renault.png'),
  CarBrand(name: 'Rolls-Royce', iconPath: '/assets/icons/rolls_royce.png'),
  CarBrand(name: 'Skoda', iconPath: '/assets/icons/skoda.png'),
  CarBrand(name: 'smart', iconPath: '/assets/icons/smart.png'),
  CarBrand(name: 'SsangYong', iconPath: '/assets/icons/ssangyong.png'),
  CarBrand(name: 'Subaru', iconPath: '/assets/icons/subaru.png'),
  CarBrand(name: 'Suzuki', iconPath: '/assets/icons/suzuki.png'),
  CarBrand(name: 'Tata', iconPath: '/assets/icons/tata.png'),
  CarBrand(name: 'Tesla', iconPath: '/assets/icons/tesla.png'),
  CarBrand(name: 'Toyota', iconPath: '/assets/icons/toyota.png'),
  CarBrand(name: 'Volkswagen', iconPath: '/assets/icons/volkswagen.png'),
  CarBrand(name: 'Volvo', iconPath: '/assets/icons/volvo.png'),
];
